MAIN = $(notdir $(basename $(wildcard ../Submissions/*.c))) #vai ter que ser adaptado para encontrar onde esta a funcao main
CFLAGS = -Wall -pedantic -Wextra
CC = gcc
#LDFLAG = -lm

#DIRECTIORIES
SRCDIR = src
OBJDIR = obj
BINDIR = bin

#SOURCE ARCHIVES
SOURCE = $(wildcard $(SRCDIR)/*.c)

#OBJECT ARCHIVES
OBJECT = $(patsubst $(SRCDIR)/%.c, $(OBJDIR)/%.o, $(SOURCE))

all: binfolder objfolder cpFile $(BINDIR)/$(MAIN).out clean

binfolder:
	@echo "Gerando pasta bin"
	mkdir -p $(BINDIR)

objfolder:
	@echo "Gerando pasta obj"
	mkdir -p $(OBJDIR)

cpFile:
	@echo "copiando arquivo submetido para a pasta src"
	cp ../Submissions/*.c ./$(SRCDIR)

bin/$(MAIN).out: $(OBJECT)
	@echo "linkando no .out"
	$(CC) $(CFLAGS) $(OBJECT) -o $@
	./$(BINDIR)/$(MAIN).out

obj/%.o: src/%.c src/header.h
	@echo "Compilando objetos"
	$(CC) $(CFLAGS) -c $< -o $@

.PHONY: clean objfolder binfolder

clean:
	rm -rf $(BINDIR)/* $(OBJDIR)/*
	rmdir $(BINDIR) $(OBJDIR)
